apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-demo
  namespace: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: app-back
        image: shamistanhuseynov1999/app-book
        env:
        - name: SPRING_DOCKER_PORT
          value: "8080"
        - name: MYSQLDB_URL
          value: jdbc:mysql://db-backend-phonebook.cjzksofpudlz.us-east-2.rds.amazonaws.com:3306/backApp
        - name: MYSQLDB_USER
          value: admin
        - name: MYSQLDB_ROOT_PASSWORD
          value: sh7513244
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bb-entrypoint
  namespace: backend-app
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
